# Operations Manager credentials to set
pcf_opsman_admin_username: user
pcf_opsman_admin_password: password

# Elastic Runtime Domain
pcf_ert_domain: doma.in

# GitHub token with repo or public_repo scope
github_token: some_token

pcf_sys_domain: sys.doma.in

prometheus_secret: prometheus-client-secret

deploy_azs: "[az1, az2]"
deploy_network: infrastructure
deploy_vm_password: #(echo -n 'YOUR_PASSWORD' | mkpasswd --method=sha-512 --password-fd=0)
deploy_nginx_ip: 1.1.1.1
