groups: []

resources:
- name: pcf-prometheus-git
  type: git
  source:
    uri: https://github.com/dlapiduz/pcf-prometheus-pipeline.git
    branch: master
- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

jobs:
- name: get-bosh-creds
  plan:
  - aggregate:
    - get: pcf-prometheus-git
    - get: tool-om
      params:
        globs:
        - "om-linux"
  - task: configure-opsman-auth
    file: pcf-prometheus-git/tasks/config-opsman-auth.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
  - task: get-creds
    file: pcf-prometheus-git/tasks/get-bosh-creds.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
