---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker-gcp

inputs:
- name: pcf-prometheus-git

params:
  pcf_ert_domain:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  pcf_sys_domain:
  prometheus_secret:

run:
  path: pcf-prometheus-git/tasks/create-uaa-creds.sh
