---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: pcf-prometheus-git
- name: tool-om

params:
  pcf_ert_domain:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:

run:
  path: pcf-prometheus-git/tasks/get-bosh-creds.sh
